export type RiskLevel = "low" | "medium" | "high";

// Raw structure generated by Gemini Planner
export interface ProjectNode {
  id: string;
  title: string;
  description: string;

  estimatedHours: number;

  riskLevel: RiskLevel;

  dependencies: string[];
}

// Raw graph generated by Gemini
export interface ProjectGraph {
  goal: string;

  nodes: ProjectNode[];
}

// Graph after CPM analysis
export interface AnalyzedProjectNode extends ProjectNode {
  earlyStart: number;

  earlyFinish: number;

  lateStart: number;

  lateFinish: number;

  slack: number;

  isCritical: boolean;
}

// Graph after deterministic backend calculations
export interface AnalyzedProjectGraph extends ProjectGraph {
  totalEstimatedHours: number;

  criticalPathHours: number;

  criticalPaths: string[][];

  bottleneckNodes: AnalyzedProjectNode[];

  isFeasible: boolean;
}
